# Bootstrap vhost used only to issue the first certificate.
server {
    listen 80;
    listen [::]:80;
    server_name chronohue.isamarin.xyz;

    root /var/www/chronohue.isamarin.xyz;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        allow all;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
